sudo: required
dist: trusty
group: edge

notifications:
  email:
    on_success: never
    on_failure: always

language: csharp
mono:
  - latest

jdk: oraclejdk8

branches:
  only:
    - master
    - /^bitnodes-.*$/

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: ./gradlew -version

script: if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$TRAVIS_TAG" ] ; then echo $TRAVIS_TAG | sed 's/\-[0-9]*\.[0-9]*\.[0-9]*//g' | xargs -I {} ./gradlew {}:check; else ./gradlew check; fi

after_success: if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$TRAVIS_TAG" ] ; then echo $TRAVIS_TAG | sed 's/\-[0-9]*\.[0-9]*\.[0-9]*//g' | xargs -I {} ./gradlew {}:bintrayUpload; elif [ -z "$TRAVIS_TAG" ] ; then ./gradlew jacocoTestReport; bash <(curl -s https://codecov.io/bash); fi

